apiVersion: v1
kind: ConfigMap
metadata:
  name: polling-backend-config
  namespace: polling
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-headless.kafka.svc.cluster.local:9092"
  SPRING_REDIS_HOST: "redis-master.redis.svc.cluster.local"
  SPRING_REDIS_PORT: "6379"
  JWT_EXPIRATION: "86400000"
  JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
