apiVersion: v1
kind: Service
metadata:
  name: polling-backend
  namespace: polling
  labels:
    app: polling-backend
spec:
  selector:
    app: polling-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
